#!/bin/bash
set -e
TESTS=""
[ "$NOTEST" = "1" ] && TESTS="-DskipTests"
mvn -e clean install $TESTS

# build a standalone jacs executable for unix
cat >jacs <<EOF
#!/bin/sh
exec java -jar \$0 "\$@"
EOF
cat target/jacs-*.jar >>jacs
chmod +x jacs
