#!/bin/bash
# build a standalone jacs executable for unix
set -e
TESTS=""
[ "$NOTEST" = "1" ] && TESTS="-DskipTests"
mvn -e clean install $TESTS
cat >jacs <<EOF
#!/usr/bin/java -jar
EOF
cat target/jacs-*.jar >>jacs
chmod +x jacs
